name: Build and deploy JAR app to Azure Web App - SpringbootDeploymentMediChain

on:
  push:
    branches:
      - JARANDXML
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Verify required files are present
        run: |
          if [[ ! -f target/*.jar ]] || [[ ! -f pom.xml ]]; then
            echo "Missing required files for deployment"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: |
            target/*.jar
            pom.xml

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SpringbootDeploymentMediChain'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CC60EBA343CD4BB6B212E6954FB06A8C }}
          package: '*.jar'
